server:
  port:
    0
spring:
  application:
    name:
      news-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name:
      org.postgresql.Driver
    url:
      jdbc:postgresql://ec2-52-49-120-150.eu-west-1.compute.amazonaws.com:5432/d122g8s7agjtv6
    username:
      iycbofqnkejrci
    password:
      8b65243d8d3544c8a574c838995165b1387fc5eb9bd1fba3d9bdb53b6a130358
  jpa:
    hibernate:
      ddl-auto:
        update
    show-sql:
      true
eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8081'

logging:
  pattern:
    console:
      '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'
