server:
  port:
    0
spring:
  application:
    name:
      news-service
  datasource:
    driver-class-name:
      org.postgresql.Driver
    url:
      jdbc:postgresql://ec2-54-77-40-202.eu-west-1.compute.amazonaws.com:5432/d9ec328geo08da
    username:
      elqynhbpgxwtyd
    password:
      608f07209db61662ae5a27c8dfc4e1ca392934c47c2ea4bd23db0450981597fd
  jpa:
    hibernate:
      ddl-auto:
        update
    show-sql:
      true
eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8081'

logging:
  pattern:
    console:
      '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'
