server:
  port:
    0
spring:
  application:
    name:
      user-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name:
      org.postgresql.Driver
    username:
      aaqecqwhuubpmg
    password:
      5f3b33791cfff5bf4bd82f100cbff8dfd6e0ec85d9c4aff7691e47fa44cb89cc
    url:
      jdbc:postgresql://ec2-52-211-182-159.eu-west-1.compute.amazonaws.com:5432/dhqenb7autoei
  jpa:
    hibernate:
      ddl-auto:
        update
    show-sql:
      true
app:
  jwtSecret:
    MegaLargeSigningSecretKeyForIITAPIApplicationMegaLargeSigningSecretKeyForIITAPIApplication
  jwtExpirationMs:
    86400000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8081/eureka/

logging:
  pattern:
    console:
      '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'