server:
  port:
    0
spring:
  application:
    name:
      user-service
  datasource:
    driver-class-name:
      org.postgresql.Driver
    username:
      gymzhyrvnpeffa
    password:
      4008e77aaa744de70794011566f034bc937cac576e215b74953307613b45a489
    url:
      jdbc:postgresql://ec2-52-49-120-150.eu-west-1.compute.amazonaws.com:5432/d19glhb8m2icr6
  jpa:
    hibernate:
      ddl-auto:
        update
    show-sql:
      true
app:
  jwtSecret:
    MegaLargeSigningSecretKeyForIITAPIApplicationMegaLargeSigningSecretKeyForIITAPIApplication
  jwtExpirationMs:
    86400000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8081/eureka/

logging:
  pattern:
    console:
      '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'