server:
  port:
    8082
spring:
  application:
    name:
      api-gateway
  datasource:
    driver-class-name:
      org.postgresql.Driver
    username:
      aaqecqwhuubpmg
    password:
      5f3b33791cfff5bf4bd82f100cbff8dfd6e0ec85d9c4aff7691e47fa44cb89cc
    url:
      jdbc:postgresql://ec2-52-211-182-159.eu-west-1.compute.amazonaws.com:5432/dhqenb7autoei
  jpa:
    hibernate:
      ddl-auto:
          update
    show-sql:
        true
  main:
    allow-bean-definition-overriding:
      true
  cloud:
    gateway:
      discovery:
        locator:
          enabled:
            true
          lower-case-service-id:
            true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/me
            - Method=GET
        - id: user-auth
          uri: lb://user-service
          predicates:
            - Path=/api/auth/signIn
            - Method=Post
        - id: schedule
          uri: lb://schedule-service
          predicates:
            - Path=/api/schedule
            - Method=GET
        - id: create-schedule
          uri: lb://schedule-service
          predicates:
            - Path=/api/schedule/create
            - Method=POST
        - id: all-news
          uri: lb://news-service
          predicates:
            - Path=/api/news/all
            - Method=GET
        - id: last-news
          uri: lb://news-service
          predicates:
            - Path=/api/news/last
            - Method=GET
        - id: news-after-id
          uri: lb://news-service
          predicates:
            - Path=/api/news/after/{id}
            - Method=GET
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/events/
            - Method=GET


eureka:
  client:
    service-url:
      default-zone: http://localhost:8081/eureka/

logging:
  pattern:
    console:
      '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'

app:
  jwtSecret:
    MegaLargeSigningSecretKeyForIITAPIApplicationMegaLargeSigningSecretKeyForIITAPIApplication
  jwtExpirationMs:
    86400000