server:
  port:
    0
spring:
  application:
    name:
      mark-service

eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8081'

logging:
  pattern:
    console:
      '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'