server:
  port:
    0
spring:
  application:
    name:
      event-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name:
      org.postgresql.Driver
    url:
      jdbc:postgresql://ec2-52-31-70-136.eu-west-1.compute.amazonaws.com:5432/dc1kjiedeomn7l
    username:
      yuftnpjsetpffr
    password:
      27bf556fedadfb802f679c7d4523dcb890bb7882f0a06384e7c709a6732010f2
  jpa:
    hibernate:
      ddl-auto:
        update
    show-sql:
      true

eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8081'

logging:
  pattern:
    console:
      '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'